#!/usr/bin/env bash
PATH=/bin:/usr/bin
addr=$@
if [ -z $REMOTE_PORT ]; then REMOTE_PORT=9999; fi;
if [ -z $LOCAL_PORT ]; then LOCAL_PORT=22; fi;
LOCALDIR=`dirname "$0"`
cd $LOCALDIR
SSHPID=`cat pid`
if [ -z "$SSHPID" ] || [ -z "`ps -p $SSHPID | grep ssh`" ]; then
  ./ssh_nopasswd $@ 

  ssh $@ -t 'if [ -z "`grep "GatewayPorts yes" /etc/ssh/sshd_config`" ]; then echo change setting "GatewayPorts yes"; sudo chmod 777 /etc/ssh/sshd_config; sudo echo "" >>/etc/ssh/sshd_config; sudo echo "GatewayPorts yes" >>/etc/ssh/sshd_config; sudo chmod 644 /etc/ssh/sshd_config; sudo /etc/init.d/ssh* restart; else echo setting already changed; fi'

  ssh -R 0.0.0.0:$REMOTE_PORT:localhost:$LOCAL_PORT -N $@ &
  echo $! >pid
	echo ""
	echo `date`: restart >>keep_alive.log
else
	echo ""
	echo ssh reverse proxy is already running
fi


